version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.8
    container_name: mosquitto
    ports:
      - ${MOSQUITTO_MQTT_PORT}:1883
      - ${MOSQUITTO_WEBSOCKET_PORT}:9001
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - shared-network
  grafana:
    image: grafana/grafana:7.4.3
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:3000 
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_SECURITY_ADMIN_PASSWORD}
    networks:
      - shared-network
networks:
  shared-network:
    external: true
