version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.8
    container_name: mosquitto
    ports:
      - ${MOSQUITTO_MQTT_PORT}:1883
      - ${MOSQUITTO_WEBSOCKET_PORT}:9001
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - shared-network
  grafana:
    image: grafana/grafana:7.4.3
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:3000 
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - shared-network
  postgres:
    image: postgres:9.6.21-alpine
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    volumes:
      # https://future-architect.github.io/articles/20200609/
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - shared-network
  influxdb:
    image: influxdb:2.0.4
    container_name: influxdb
    ports:
      - ${INFLUXDB_PORT}:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    networks:
      - shared-network
  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    networks:
      - shared-network
networks:
  shared-network:
    external: true
