# copied from container default
global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  group_by: ['alertname', 'datacenter', 'app']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    text: 'https://prometheus.io/docs/alerting/latest/notification_examples/#customizing-slack-notifications'
